[cpa-gateway]
backend = polling
enabled = true
port = 8443
filter = cpa-gateway
logpath = /var/log/nginx/cpa_gateway.access.log tail
maxretry = 20
findtime = 600
bantime = 3600
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 604800
ignoreip = 127.0.0.1/8 ::1
