#!/usr/bin/env python3
"""Attribute CPA gateway failures to the layer that produced them.

Four independent layers can answer 429, and a fifth can answer 5xx. Only one of
them is normally at fault, and the fixes are mutually exclusive, so the layer
must be proven before anything is changed. This module encodes the
discriminating rules so the answer stops depending on whoever reads the logs.

Layer table (see docs/runbooks/cpa-failure-triage.md for the full narrative):

| Layer                   | Discriminator                                                    |
|-------------------------|------------------------------------------------------------------|
| `local_gate`            | 429 whose latency equals the local gate wait budget (e.g. 45.0 s) |
| `admission_queue_timeout` | 429 whose latency equals the admission queue budget (e.g. 120.0 s) |
| `admission_fast_reject` | 429 answered in milliseconds (cooldown / queue full)             |
| `upstream_capacity`     | 5xx generated by the upstream (overloaded / auth unavailable)     |
| `dead_route`            | 5xx on a model alias whose upstream refuses to serve it           |
| `client_abort`          | 499 - the client gave up; not an upstream fault                   |
| `client_error`          | 4xx from auth / model routing / request shape                     |
| `slow_success`          | 200 that took longer than the slow-path threshold                 |

The authoritative local view is the Cockpit request log database
(`~/.antigravity_cockpit/codex_local_access_logs.sqlite`, table `request_logs`),
which carries `http_status`, `error_category`, `latency_ms` and
`requested_model` per request. A local-gate rejection never leaves the machine,
so it appears here and **not** in the gateway's nginx access log; a non-zero
`local_gate` count with few remote 429s is therefore the expected, consistent
shape rather than a contradiction.

Read-only: the database is opened with `mode=ro` and nothing is written.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sqlite3
import sys
from dataclasses import dataclass, field
from typing import Any, Sequence

# Layer identifiers. Kept as plain strings so the JSON output stays stable and
# readable in a terminal.
LOCAL_GATE = "local_gate"
ADMISSION_QUEUE = "admission_queue_timeout"
ADMISSION_FAST = "admission_fast_reject"
UPSTREAM_CAPACITY = "upstream_capacity"
DEAD_ROUTE = "dead_route"
CLIENT_ABORT = "client_abort"
CLIENT_ERROR = "client_error"
SLOW_SUCCESS = "slow_success"
HEALTHY = "healthy"
UNCLASSIFIED = "unclassified"

LAYER_ORDER: tuple[str, ...] = (
    LOCAL_GATE,
    ADMISSION_QUEUE,
    ADMISSION_FAST,
    UPSTREAM_CAPACITY,
    DEAD_ROUTE,
    CLIENT_ERROR,
    CLIENT_ABORT,
    SLOW_SUCCESS,
    UNCLASSIFIED,
    HEALTHY,
)

# Model aliases whose upstream is *currently* known to refuse service. Keep
# this list empty until a fresh route-specific probe and the deployed manifest
# agree that an alias is dead. Historical 5xx samples belong to
# ``upstream_capacity`` (or the posture audit), otherwise a route that has
# recovered is permanently misreported as a local routing defect.
DEAD_ROUTES: dict[str, str] = {}

DEFAULT_DB = (
    pathlib.Path.home() / ".antigravity_cockpit" / "codex_local_access_logs.sqlite"
)
DEFAULT_COLLECTION = (
    pathlib.Path.home() / ".antigravity_cockpit" / "codex_local_access.json"
)

# error_category values written by the Cockpit sidecar.
CATEGORY_RATE_LIMIT = "quota_or_rate_limit"
CLIENT_ERROR_CATEGORIES = frozenset(
    {"auth_failed", "model_not_available", "request_failed"}
)


@dataclass(frozen=True)
class Budgets:
    """Configured wait budgets, in milliseconds.

    These are fingerprints, not preferences: a rejection whose latency equals a
    budget is that layer refusing. They must track the live configuration or the
    classifier will silently stop matching, which is why `load_budgets` reads the
    gate value from the Cockpit collection rather than hardcoding it.
    """

    gate_wait_ms: int = 45000
    queue_timeout_ms: int = 120000
    tolerance_ms: int = 1500
    fast_reject_ms: int = 5000
    slow_ms: int = 60000


@dataclass
class Row:
    timestamp_ms: int
    status: int | None
    category: str
    latency_ms: int
    model: str


def classify(
    status: int | None,
    category: str,
    latency_ms: int,
    model: str,
    budgets: Budgets,
) -> str:
    """Return the layer identifier for one request log row.

    Order matters. The dead-route check precedes the generic 5xx check because a
    dead route also answers 5xx, and reporting it as plain upstream capacity
    would hide a defect we can actually fix.
    """

    if status == 200:
        return SLOW_SUCCESS if latency_ms >= budgets.slow_ms else HEALTHY
    if status == 499:
        return CLIENT_ABORT
    if category == CATEGORY_RATE_LIMIT or status == 429:
        # A rejection that waits out a budget necessarily arrives at or after
        # that budget, so the admission fingerprint is a lower bound. The gate
        # fingerprint is a window: the gate refuses before contacting upstream,
        # so its own overhead is tens of milliseconds, not seconds. Ordering the
        # gate check first keeps a 120 s admission timeout from matching it.
        if (
            budgets.gate_wait_ms
            <= latency_ms
            <= budgets.gate_wait_ms + budgets.tolerance_ms
        ):
            return LOCAL_GATE
        if latency_ms >= budgets.queue_timeout_ms - budgets.tolerance_ms:
            return ADMISSION_QUEUE
        if latency_ms < budgets.fast_reject_ms:
            return ADMISSION_FAST
        # A 429 that matches neither budget is a shape we have not explained
        # yet. Surface it instead of guessing.
        return UNCLASSIFIED
    if status in (500, 502, 503):
        if model in DEAD_ROUTES:
            return DEAD_ROUTE
        return UPSTREAM_CAPACITY
    if category in CLIENT_ERROR_CATEGORIES:
        return CLIENT_ERROR
    return UNCLASSIFIED


@dataclass
class LayerReport:
    layer: str
    count: int = 0
    latency_ms: list[int] = field(default_factory=list)
    examples: list[str] = field(default_factory=list)

    def to_json(self) -> dict[str, Any]:
        return {
            "layer": self.layer,
            "count": self.count,
            "latency_ms": {
                "min": min(self.latency_ms) if self.latency_ms else None,
                "max": max(self.latency_ms) if self.latency_ms else None,
            },
            "examples": self.examples,
        }


def summarize(
    rows: Sequence[Row], budgets: Budgets, example_limit: int = 3
) -> dict[str, LayerReport]:
    reports: dict[str, LayerReport] = {name: LayerReport(name) for name in LAYER_ORDER}
    for row in rows:
        layer = classify(row.status, row.category, row.latency_ms, row.model, budgets)
        report = reports[layer]
        report.count += 1
        report.latency_ms.append(row.latency_ms)
        if len(report.examples) < example_limit:
            stamp = _format_stamp(row.timestamp_ms)
            report.examples.append(
                f"{stamp} status={row.status} model={row.model} latency={row.latency_ms}ms"
            )
    return reports


def _format_stamp(timestamp_ms: int) -> str:
    import datetime

    return datetime.datetime.fromtimestamp(timestamp_ms / 1000).strftime(
        "%m-%d %H:%M:%S"
    )


def load_budgets(
    collection_path: pathlib.Path | None, overrides: dict[str, int]
) -> Budgets:
    """Derive the wait fingerprints from the live Cockpit collection when present.

    `accountConcurrencyWaitMs` is a user-facing setting, so reading it here keeps
    the classifier honest after the budget is retuned. The admission queue budget
    lives on the remote host and is passed in explicitly.
    """

    gate = Budgets().gate_wait_ms
    if collection_path is not None and collection_path.exists():
        try:
            data = json.loads(collection_path.read_text(encoding="utf-8"))
            candidate = data.get("accountConcurrencyWaitMs")
            if isinstance(candidate, int) and candidate > 0:
                gate = candidate
        except (OSError, ValueError):
            pass
    return Budgets(
        gate_wait_ms=overrides.get("gate_wait_ms", gate),
        queue_timeout_ms=overrides.get("queue_timeout_ms", Budgets().queue_timeout_ms),
        tolerance_ms=overrides.get("tolerance_ms", Budgets().tolerance_ms),
        fast_reject_ms=overrides.get("fast_reject_ms", Budgets().fast_reject_ms),
        slow_ms=overrides.get("slow_ms", Budgets().slow_ms),
    )


def read_rows(db_path: pathlib.Path, since_ms: int) -> list[Row]:
    """Read the request log read-only. Returns [] when the database is absent."""

    if not db_path.exists():
        return []
    uri = f"file:{db_path.as_posix()}?mode=ro"
    connection = sqlite3.connect(uri, uri=True)
    try:
        cursor = connection.cursor()
        rows: list[Row] = []
        for timestamp, status, category, latency, model in cursor.execute(
            "select timestamp, http_status, error_category, latency_ms, requested_model "
            "from request_logs where timestamp >= ? order by timestamp",
            (since_ms,),
        ):
            rows.append(
                Row(
                    timestamp_ms=int(timestamp),
                    status=int(status) if status is not None else None,
                    category=str(category or ""),
                    latency_ms=int(latency or 0),
                    model=str(model or ""),
                )
            )
        return rows
    finally:
        connection.close()


REMOTE_KEYS = (
    "DOCTOR_CONTRACT_OK",
    "DOCTOR_CONTRACT_FAILED",
    "cooldown_state",
    "luna_state",
    "oauth_days_left",
    "retained_overload_request_files",
    "overload_markers",
)


def parse_doctor(text: str) -> dict[str, Any]:
    """Extract the few remote-side facts that decide the verdict.

    The doctor prints one JSON line for the gateway-statuses section, and
    `statuses_by_client_class` / `statuses_by_hour` live *inside* it, not on
    lines of their own, so they are read from the parsed object.
    """

    facts: dict[str, Any] = {}
    for key in REMOTE_KEYS:
        if key in ("DOCTOR_CONTRACT_OK", "DOCTOR_CONTRACT_FAILED"):
            if re.search(rf"^{key}$", text, re.MULTILINE):
                facts["contract"] = key
            continue
        match = re.search(rf"^{key}=(.*)$", text, re.MULTILINE)
        if match:
            facts[key] = match.group(1).strip()
    for block_key, pattern in (
        ("gateway_statuses", r'\{"statuses":'),
        ("overload", r'\{"retained_overload_request_files"'),
    ):
        match = re.search(pattern + r".*", text)
        if not match:
            continue
        try:
            facts[block_key] = json.loads(match.group(0).strip().splitlines()[0])
        except ValueError:
            continue
    statuses = facts.get("gateway_statuses")
    if isinstance(statuses, dict):
        for nested in (
            "statuses_by_client_class",
            "statuses_by_hour",
            "admission_429_shape",
        ):
            if nested in statuses:
                facts[nested] = statuses[nested]
    return facts


def recommendations(reports: dict[str, LayerReport], budgets: Budgets) -> list[str]:
    lines: list[str] = []
    if reports[LOCAL_GATE].count:
        lines.append(
            "local_gate: the local gate refused after its full wait budget. Root cause is "
            "usually upstream turns holding every slot; do NOT raise the concurrency limit "
            "- the shared lane is normally saturated too, so requests would only move from "
            "a fast failure to a queue timeout."
        )
    if reports[ADMISSION_QUEUE].count:
        lines.append(
            "admission_queue_timeout: requests queued the whole admission budget and were "
            "then refused. This shape appears when upstream turns slow down enough that the "
            "queue cannot drain in time. Do not retune admission on a degraded window."
        )
    if reports[UPSTREAM_CAPACITY].count:
        lines.append(
            "upstream_capacity: the upstream itself answered 5xx (overloaded / auth "
            "unavailable). Nothing local fixes this; reduce request rate or use a different "
            "lane."
        )
    if reports[DEAD_ROUTE].count:
        for model, reason in DEAD_ROUTES.items():
            lines.append(f"dead_route: {model} - {reason}")
    if reports[UNCLASSIFIED].count:
        lines.append(
            "unclassified: some rows match no known budget or status shape. Investigate "
            "before trusting the other counts."
        )
    slow = reports[SLOW_SUCCESS]
    if slow.count and slow.latency_ms:
        ordered = sorted(slow.latency_ms)
        lines.append(
            f"slow_success: {slow.count} successful requests above {budgets.slow_ms} ms "
            f"(max {ordered[-1]} ms). Slowness is dominated by upstream generation time, "
            "not by the local gateway."
        )
    if not lines:
        lines.append("No attributed failures in the window.")
    return lines


def render_remote(facts: dict[str, Any]) -> list[str]:
    """Print only the remote facts a reader acts on, never a raw log dump."""

    if not facts:
        return []
    out = ["-- remote facts --"]
    headline = "  ".join(
        f"{key}={facts[key]}"
        for key in ("contract", "cooldown_state", "luna_state", "oauth_days_left")
        if key in facts
    )
    if headline:
        out.append(f"  {headline}")
    overload = facts.get("overload")
    if isinstance(overload, dict):
        out.append(
            "  retained_overload_request_files={}  overload_markers={}".format(
                overload.get("retained_overload_request_files"),
                overload.get("overload_markers"),
            )
        )
        lanes = overload.get("auth_unavailable_by_lane")
        if lanes:
            out.append(f"  auth_unavailable_by_lane={lanes}")
    by_class = facts.get("statuses_by_client_class")
    if isinstance(by_class, dict):
        external = {
            k.split("/", 1)[1]: v
            for k, v in by_class.items()
            if k.startswith("external/")
        }
        loopback = {
            k.split("/", 1)[1]: v
            for k, v in by_class.items()
            if k.startswith("loopback/")
        }
        out.append(f"  external statuses={external}")
        out.append(
            f"  loopback statuses={loopback}  (probe/load-test residue, not production)"
        )
    shape = facts.get("admission_429_shape")
    if shape:
        out.append(f"  admission_429_shape={shape}")
    by_hour = facts.get("statuses_by_hour")
    if isinstance(by_hour, dict) and by_hour:
        recent = list(sorted(by_hour.items()))[-4:]
        out.append("  recent hours (UTC):")
        for hour, values in recent:
            detail = " ".join(
                f"{k}={v}" for k, v in sorted(values.items()) if k != "total"
            )
            out.append(f"    {hour} total={values.get('total')} {detail}")
    return out


def render(
    reports: dict[str, LayerReport],
    facts: dict[str, Any],
    budgets: Budgets,
    hours: float,
) -> str:
    out: list[str] = []
    out.append(f"== CPA failure triage (last {hours:g}h) ==")
    out.append(
        f"fingerprints: local_gate={budgets.gate_wait_ms}ms  "
        f"admission_queue={budgets.queue_timeout_ms}ms  slow>={budgets.slow_ms}ms"
    )
    out.extend(render_remote(facts))
    out.append("-- layers --")
    for name in LAYER_ORDER:
        report = reports[name]
        if not report.count:
            continue
        span = f"{min(report.latency_ms)}..{max(report.latency_ms)}ms"
        out.append(f"  {name:<24} n={report.count:<5} latency {span}")
        for example in report.examples:
            out.append(f"      {example}")
    out.append("-- verdict --")
    for line in recommendations(reports, budgets):
        out.append(f"  * {line}")
    return "\n".join(out)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Attribute CPA gateway failures to the layer that produced them.",
    )
    parser.add_argument("--db", type=pathlib.Path, default=DEFAULT_DB)
    parser.add_argument("--collection", type=pathlib.Path, default=DEFAULT_COLLECTION)
    parser.add_argument("--hours", type=float, default=24.0)
    parser.add_argument(
        "--doctor",
        type=pathlib.Path,
        default=None,
        help="doctor output file to fold in the remote-side facts",
    )
    parser.add_argument("--gate-wait-ms", type=int, default=None)
    parser.add_argument("--queue-timeout-ms", type=int, default=None)
    parser.add_argument("--slow-ms", type=int, default=None)
    parser.add_argument("--json", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    overrides: dict[str, int] = {}
    for key, value in (
        ("gate_wait_ms", args.gate_wait_ms),
        ("queue_timeout_ms", args.queue_timeout_ms),
        ("slow_ms", args.slow_ms),
    ):
        if value is not None:
            overrides[key] = int(value)

    budgets = load_budgets(args.collection, overrides)
    import datetime

    since_ms = int(
        (datetime.datetime.now() - datetime.timedelta(hours=args.hours)).timestamp()
        * 1000
    )
    # A locked or corrupt database must exit 2 (the tool's "cannot check"
    # code). An unhandled sqlite3.Error would trace and exit 1, which no
    # caller can distinguish from a classified-failures run.
    try:
        rows = read_rows(args.db, since_ms)
    except sqlite3.Error as exc:
        print(
            f"cannot read request log database {args.db}: {type(exc).__name__}: {exc}",
            file=sys.stderr,
        )
        return 2
    if not rows and not args.db.exists():
        print(f"no request log database at {args.db}", file=sys.stderr)
        print(
            "pass --db, or run this on the machine that hosts the Cockpit sidecar",
            file=sys.stderr,
        )
        return 2

    facts: dict[str, Any] = {}
    if args.doctor is not None and args.doctor.exists():
        facts = parse_doctor(args.doctor.read_text(encoding="utf-8"))

    reports = summarize(rows, budgets)
    if args.json:
        print(
            json.dumps(
                {
                    "hours": args.hours,
                    "budgets": {
                        "gate_wait_ms": budgets.gate_wait_ms,
                        "queue_timeout_ms": budgets.queue_timeout_ms,
                        "slow_ms": budgets.slow_ms,
                    },
                    "rows": len(rows),
                    "layers": [reports[name].to_json() for name in LAYER_ORDER],
                    "remote": facts,
                    "verdict": recommendations(reports, budgets),
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return 0
    print(render(reports, facts, budgets, args.hours))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
